/*
 * Generated by python/generate_test_vectors.py.
 * profile: Animagus-AES-v1
 * profile version: 1
 * normative: yes
 * provenance: Normative Animagus-AES-v1 vectors generated by this repository
 */
#pragma once

#include "testvec.h"

struct animagus_testvec {
    struct testvec_buffer key;
    struct testvec_buffer tweak;
    struct testvec_buffer plaintext;
    struct testvec_buffer ciphertext;
};

struct animagus_tweak_testvec {
    struct testvec_buffer key;
    struct testvec_buffer nonce;
    struct testvec_buffer ad;
    struct testvec_buffer tweak;
};

extern const struct animagus_testvec animagus_aes128_tv[];
extern const size_t animagus_aes128_tv_count;
extern const struct animagus_testvec animagus_aes192_tv[];
extern const size_t animagus_aes192_tv_count;
extern const struct animagus_testvec animagus_aes256_tv[];
extern const size_t animagus_aes256_tv_count;

extern const struct animagus_tweak_testvec animagus_aes128_tweak_tv[];
extern const size_t animagus_aes128_tweak_tv_count;
extern const struct animagus_tweak_testvec animagus_aes192_tweak_tv[];
extern const size_t animagus_aes192_tweak_tv_count;
extern const struct animagus_tweak_testvec animagus_aes256_tweak_tv[];
extern const size_t animagus_aes256_tweak_tv_count;
