"""Generate deterministic vectors for the repository's Animagus profile."""

import argparse
import json
import pathlib
import random
import sys


ROOT = pathlib.Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from python.animagus import (  # noqa: E402
    PROFILE_NAME,
    PROFILE_VERSION,
    derive_tweak,
    encrypt,
)


KEY_LENGTHS = (16, 24, 32)
TWEAK_LENGTHS = (0, 16)
MESSAGE_LENGTHS = (32, 33, 47, 48, 49, 64, 512, 4096)
NONCE_AD_LENGTHS = ((0, 0), (12, 0), (12, 13), (12, 32), (16, 0), (16, 47))
PROFILE = PROFILE_NAME
PROVENANCE = "Normative Animagus-AES-v1 vectors generated by this repository"
JSON_PATHS = {
    key_len: ROOT / f"test_vectors/ours/Animagus/Animagus_AES{key_len * 8}.json"
    for key_len in KEY_LENGTHS
}
C_PATH = ROOT / "test_vectors/converted/cstruct/animagus_testvecs.c"
H_PATH = ROOT / "test_vectors/converted/cstruct/animagus_testvecs.h"


def _random_bytes(source: random.Random, length: int) -> bytes:
    return bytes(source.randrange(0x100) for _ in range(length))


def _vectors(key_len: int) -> dict[str, object]:
    cases = []
    for tweak_len in TWEAK_LENGTHS:
        for message_len in MESSAGE_LENGTHS:
            case_index = 0
            source = random.Random(
                repr((key_len, tweak_len, message_len, case_index))
            )
            key = _random_bytes(source, key_len)
            tweak = _random_bytes(source, tweak_len)
            plaintext = _random_bytes(source, message_len)
            if not cases:
                ciphertext, trace = encrypt(key, tweak, plaintext, trace=True)
            else:
                ciphertext = encrypt(key, tweak, plaintext)
                trace = None
            case = {
                "ciphertext": ciphertext.hex(),
                "key": key.hex(),
                "plaintext": plaintext.hex(),
                "tweak": tweak.hex(),
            }
            if trace is not None:
                case["trace"] = trace
            cases.append(case)
    tweak_cases = []
    for nonce_len, ad_len in NONCE_AD_LENGTHS:
        source = random.Random(repr((key_len, "tweak", nonce_len, ad_len)))
        key = _random_bytes(source, key_len)
        nonce = _random_bytes(source, nonce_len)
        ad = _random_bytes(source, ad_len)
        tweak_cases.append(
            {
                "ad": ad.hex(),
                "key": key.hex(),
                "nonce": nonce.hex(),
                "tweak": derive_tweak(key, nonce, ad).hex(),
            }
        )
    return {
        "algorithm": f"Animagus-AES{key_len * 8}",
        "cases": cases,
        "normative": True,
        "profile": PROFILE,
        "profile_version": PROFILE_VERSION,
        "provenance": PROVENANCE,
        "tweak_cases": tweak_cases,
    }


def _json_bytes(vectors: dict[str, object]) -> bytes:
    return (json.dumps(vectors, indent=2, sort_keys=True) + "\n").encode("ascii")


def _c_bytes(data: bytes, indent: str = "    ") -> list[str]:
    return [
        indent + ", ".join(f"0x{value:02x}" for value in data[offset:offset + 12]) + ","
        for offset in range(0, len(data), 12)
    ]


def _header_bytes() -> bytes:
    lines = [
        "/*",
        " * Generated by python/generate_test_vectors.py.",
        f" * profile: {PROFILE}",
        f" * profile version: {PROFILE_VERSION}",
        " * normative: yes",
        f" * provenance: {PROVENANCE}",
        " */",
        "#pragma once",
        "",
        '#include "testvec.h"',
        "",
        "struct animagus_testvec {",
        "    struct testvec_buffer key;",
        "    struct testvec_buffer tweak;",
        "    struct testvec_buffer plaintext;",
        "    struct testvec_buffer ciphertext;",
        "};",
        "",
        "struct animagus_tweak_testvec {",
        "    struct testvec_buffer key;",
        "    struct testvec_buffer nonce;",
        "    struct testvec_buffer ad;",
        "    struct testvec_buffer tweak;",
        "};",
        "",
        "extern const struct animagus_testvec animagus_aes128_tv[];",
        "extern const size_t animagus_aes128_tv_count;",
        "extern const struct animagus_testvec animagus_aes192_tv[];",
        "extern const size_t animagus_aes192_tv_count;",
        "extern const struct animagus_testvec animagus_aes256_tv[];",
        "extern const size_t animagus_aes256_tv_count;",
        "",
        "extern const struct animagus_tweak_testvec animagus_aes128_tweak_tv[];",
        "extern const size_t animagus_aes128_tweak_tv_count;",
        "extern const struct animagus_tweak_testvec animagus_aes192_tweak_tv[];",
        "extern const size_t animagus_aes192_tweak_tv_count;",
        "extern const struct animagus_tweak_testvec animagus_aes256_tweak_tv[];",
        "extern const size_t animagus_aes256_tweak_tv_count;",
        "",
    ]
    return "\n".join(lines).encode("ascii")


def _c_buffer(
    lines: list[str], symbol: str, data: bytes
) -> str:
    if not data:
        return "{ .len = 0U, .data = NULL }"
    lines.append(f"static const uint8_t {symbol}[] = {{")
    lines.extend(_c_bytes(data))
    lines.extend(["};", ""])
    return f"{{ .len = sizeof({symbol}), .data = {symbol} }}"


def _c_source_bytes(all_vectors: dict[int, dict[str, object]]) -> bytes:
    lines = [
        "/*",
        " * Generated by python/generate_test_vectors.py.",
        f" * profile: {PROFILE}",
        f" * profile version: {PROFILE_VERSION}",
        " * normative: yes",
        f" * provenance: {PROVENANCE}",
        " */",
        '#include "animagus_testvecs.h"',
        "",
    ]
    groups: dict[int, list[dict[str, str]]] = {}
    tweak_groups: dict[int, list[dict[str, str]]] = {}
    for key_len, vectors in all_vectors.items():
        group = []
        for index, case in enumerate(vectors["cases"]):
            buffers = {}
            for field in ("key", "tweak", "plaintext", "ciphertext"):
                symbol = f"animagus_aes{key_len * 8}_{index}_{field}"
                buffers[field] = _c_buffer(lines, symbol, bytes.fromhex(case[field]))
            group.append(buffers)
        groups[key_len] = group
        tweak_group = []
        for index, case in enumerate(vectors["tweak_cases"]):
            buffers = {}
            for field in ("key", "nonce", "ad", "tweak"):
                symbol = f"animagus_aes{key_len * 8}_tweak_{index}_{field}"
                buffers[field] = _c_buffer(lines, symbol, bytes.fromhex(case[field]))
            tweak_group.append(buffers)
        tweak_groups[key_len] = tweak_group

    for key_len, entries in groups.items():
        prefix = f"animagus_aes{key_len * 8}_tv"
        lines.append(f"const struct animagus_testvec {prefix}[] = {{")
        for buffers in entries:
            lines.extend(
                [
                    "    {",
                    f"        .key = {buffers['key']},",
                    f"        .tweak = {buffers['tweak']},",
                    f"        .plaintext = {buffers['plaintext']},",
                    f"        .ciphertext = {buffers['ciphertext']},",
                    "    },",
                ]
            )
        lines.extend(
            [
                "};",
                f"const size_t {prefix}_count = sizeof({prefix}) / sizeof({prefix}[0]);",
                "",
            ]
        )

    for key_len, entries in tweak_groups.items():
        prefix = f"animagus_aes{key_len * 8}_tweak_tv"
        lines.append(f"const struct animagus_tweak_testvec {prefix}[] = {{")
        for buffers in entries:
            lines.extend(
                [
                    "    {",
                    f"        .key = {buffers['key']},",
                    f"        .nonce = {buffers['nonce']},",
                    f"        .ad = {buffers['ad']},",
                    f"        .tweak = {buffers['tweak']},",
                    "    },",
                ]
            )
        lines.extend(
            [
                "};",
                f"const size_t {prefix}_count = sizeof({prefix}) / sizeof({prefix}[0]);",
                "",
            ]
        )
    return "\n".join(lines).encode("ascii")


def _generated_files() -> dict[pathlib.Path, bytes]:
    all_vectors = {key_len: _vectors(key_len) for key_len in KEY_LENGTHS}
    files = {
        JSON_PATHS[key_len]: _json_bytes(vectors)
        for key_len, vectors in all_vectors.items()
    }
    files[H_PATH] = _header_bytes()
    files[C_PATH] = _c_source_bytes(all_vectors)
    return files


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    generated = _generated_files()
    if args.check:
        stale = [
            path for path, contents in generated.items()
            if not path.is_file() or path.read_bytes() != contents
        ]
        for path in stale:
            print(f"{path} is out of date", file=sys.stderr)
        if stale:
            return 1
        print(f"All {len(generated)} generated vector files are up to date")
        return 0

    for path, contents in generated.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(contents)
        print(f"Wrote {path.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
