"""Generate independent Animagus-AES-v1 core-HMAC framing fixtures."""

import argparse
import hashlib
import hmac
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "test_vectors/ours/HMAC_SHA3_256_ANIMAGUS_V1.json"
DEFAULT_C_HEADER = (
    ROOT / "test_vectors/converted/cstruct/hmac_sha3_animagus_v1_testvecs.h"
)
CORE_LABEL = b"Animagus-AES-v1/CORE"
PROFILE = "Animagus-AES-v1 core-HMAC framing"
PROVENANCE = "Repository-generated non-normative primitive fixtures"


def _digest(key: bytes, tail: bytes, domain: int, tweak: bytes) -> bytes:
    framed = (
        CORE_LABEL
        + bytes((domain,))
        + len(tail).to_bytes(8, "big")
        + len(tweak).to_bytes(8, "big")
        + tail
        + tweak
    )
    return hmac.new(key, framed, hashlib.sha3_256).digest()


def _vectors() -> dict[str, object]:
    cases = []
    for key_length in (16, 24, 32):
        key = bytes(range(key_length))
        for tail in (b"", b"\x00", bytes(range(33))):
            for domain in (0x01, 0x02):
                for tweak in (b"", bytes(range(16))):
                    cases.append(
                        {
                            "digest": _digest(key, tail, domain, tweak).hex(),
                            "domain": domain,
                            "key": key.hex(),
                            "tail": tail.hex(),
                            "tweak": tweak.hex(),
                        }
                    )
    return {
        "algorithm": "HMAC-SHA3-256 Animagus-AES-v1 core frame",
        "cases": cases,
        "normative": False,
        "profile": PROFILE,
        "profile_version": 1,
        "provenance": PROVENANCE,
    }


def _encoded_vectors(vectors: dict[str, object]) -> bytes:
    return (json.dumps(vectors, indent=2, sort_keys=True) + "\n").encode("ascii")


def _format_bytes(data: bytes, indent: str = "    ") -> str:
    rows = []
    for offset in range(0, len(data), 12):
        chunk = data[offset:offset + 12]
        rows.append(indent + ", ".join(f"0x{value:02x}" for value in chunk) + ",")
    return "\n".join(rows)


def _encoded_c_header(vectors: dict[str, object]) -> bytes:
    grouped: dict[tuple[str, str, str], dict[int, str]] = {}
    for case in vectors["cases"]:
        identity = (case["key"], case["tail"], case["tweak"])
        grouped.setdefault(identity, {})[case["domain"]] = case["digest"]

    lines = [
        "/*",
        " * Generated by python/generate_primitive_vectors.py.",
        f" * profile: {vectors['profile']}",
        f" * profile version: {vectors['profile_version']}",
        " * normative: no",
        f" * provenance: {vectors['provenance']}",
        " */",
        "#pragma once",
        "",
        '#include "testvec.h"',
        "",
        "struct hmac_sha3_animagus_v1_testvec {",
        "    struct testvec_buffer key;",
        "    struct testvec_buffer tail;",
        "    struct testvec_buffer tweak;",
        "    struct testvec_buffer plaintext_digest;",
        "    struct testvec_buffer ciphertext_digest;",
        "};",
        "",
    ]
    entries = []
    for index, ((key_hex, tail_hex, tweak_hex), digests) in enumerate(grouped.items()):
        values = {
            "key": bytes.fromhex(key_hex),
            "tail": bytes.fromhex(tail_hex),
            "tweak": bytes.fromhex(tweak_hex),
            "plaintext_digest": bytes.fromhex(digests[0x01]),
            "ciphertext_digest": bytes.fromhex(digests[0x02]),
        }
        buffers = {}
        for name, data in values.items():
            if data:
                symbol = f"hmac_sha3_animagus_v1_{index}_{name}"
                lines.extend([
                    f"static const uint8_t {symbol}[] = {{",
                    _format_bytes(data),
                    "};",
                    "",
                ])
                buffers[name] = f"{{ sizeof({symbol}), {symbol} }}"
            else:
                buffers[name] = "{ 0U, NULL }"
        entries.append(
            "    {\n"
            f"        {buffers['key']},\n"
            f"        {buffers['tail']},\n"
            f"        {buffers['tweak']},\n"
            f"        {buffers['plaintext_digest']},\n"
            f"        {buffers['ciphertext_digest']},\n"
            "    },"
        )
    lines.append(
        "static const struct hmac_sha3_animagus_v1_testvec "
        "hmac_sha3_animagus_v1_testvecs[] = {"
    )
    lines.extend(entries)
    lines.extend(["};", ""])
    return "\n".join(lines).encode("ascii")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--c-header", type=pathlib.Path)
    args = parser.parse_args()
    vectors = _vectors()
    generated = _encoded_vectors(vectors)
    header_path = args.c_header
    if args.check and header_path is None:
        header_path = DEFAULT_C_HEADER
    generated_header = _encoded_c_header(vectors)
    if args.check:
        if not OUTPUT.is_file() or OUTPUT.read_bytes() != generated:
            print(f"{OUTPUT} is out of date", file=sys.stderr)
            return 1
        if (header_path is not None and
                (not header_path.is_file() or
                 header_path.read_bytes() != generated_header)):
            print(f"{header_path} is out of date", file=sys.stderr)
            return 1
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_bytes(generated)
    if header_path is not None:
        header_path.parent.mkdir(parents=True, exist_ok=True)
        header_path.write_bytes(generated_header)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
